CREATE TABLE PET_REGISTRY (
    PET_ID INT PRIMARY KEY,
    PET_NAME VARCHAR(50),
    BIRTH_DATE DATE,
    WEIGHT_KG DECIMAL(10, 2),
    COLOR VARCHAR(50)
);

-- Inserção de dados na tabela PET_REGISTRY
INSERT INTO PET_REGISTRY VALUES (1, 'Buddy', '2018-03-12', 9.5, 'marrom');
INSERT INTO PET_REGISTRY VALUES (2, 'Luna', '2019-05-21', 7.8, 'preto');
INSERT INTO PET_REGISTRY VALUES (3, 'Rex', '2017-08-15', 12.3, 'amarelo');
INSERT INTO PET_REGISTRY VALUES (4, 'Misty', '2020-02-10', 8.9, 'cinza');
INSERT INTO PET_REGISTRY VALUES (5, 'Simba', '2016-11-30', 10.2, 'marrom');
INSERT INTO PET_REGISTRY VALUES (6, 'Whiskers', '2019-07-05', 6.5, 'preto');
INSERT INTO PET_REGISTRY VALUES (7, 'Oliver', '2018-04-18', 5.7, 'branco');
INSERT INTO PET_REGISTRY VALUES (8, 'Tiger', '2015-09-25', 11.8, 'laranja');
INSERT INTO PET_REGISTRY VALUES (9, 'Rocky', '2016-01-15', 14.2, 'preto');
INSERT INTO PET_REGISTRY VALUES (10, 'Fido', '2021-03-07', 6.9, 'bege');

-- Atualizações na tabela PET_REGISTRY
UPDATE PET_REGISTRY
SET PET_NAME = 'Max'
WHERE PET_NAME = 'Charlie';

UPDATE PET_REGISTRY
SET WEIGHT_KG = 11.2
WHERE PET_NAME = 'Luna';

UPDATE PET_REGISTRY
SET COLOR = 'amarelo'
WHERE COLOR IN ('preto', 'marrom', 'branco', 'bege', 'cinza');

-- Adição de colunas na tabela PET_REGISTRY
ALTER TABLE PET_REGISTRY
ADD HEIGHT_CM DECIMAL(10, 2);

ALTER TABLE PET_REGISTRY
ADD REMARKS VARCHAR(255);

-- Remoções de registros na tabela PET_REGISTRY
DELETE FROM PET_REGISTRY
WHERE WEIGHT_KG > 15;

DELETE FROM PET_REGISTRY
WHERE PET_NAME LIKE 'S%';

-- Remoção de coluna na tabela PET_REGISTRY
ALTER TABLE PET_REGISTRY
DROP COLUMN COLOR;

-- Modificação de coluna na tabela PET_REGISTRY
ALTER TABLE PET_REGISTRY
MODIFY PET_NAME VARCHAR(80);

-- Remoção de registros na tabela PET_REGISTRY
DELETE FROM PET_REGISTRY
WHERE PET_NAME IN ('Fido', 'Misty', 'Rocky', 'Simba', 'Tiger', 'Whiskers', 'Oliver');

-- Remoção da tabela PET_REGISTRY
DROP TABLE PET_REGISTRY;